spring.application.name=auth-service
server.port=${SERVER_PORT:8081}

# Comunicación con core-service
core-service.url=${CORE_SERVICE_URL:http://localhost:8083}

# Base de datos
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3307/playland_auth?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:root}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:123456}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA
spring.jpa.hibernate.ddl-auto=${SPRING_JPA_HIBERNATE_DDL_AUTO:update}
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Keycloak
keycloak.server-url=${KEYCLOAK_SERVER_URL:http://localhost:9090}
keycloak.realm=${KEYCLOAK_REALM:playland-realm}
keycloak.admin.username=${KEYCLOAK_ADMIN_USERNAME:admin}
keycloak.admin.password=${KEYCLOAK_ADMIN_PASSWORD:admin123}
keycloak.admin.client-id=${KEYCLOAK_ADMIN_CLIENT_ID:admin-cli}

# Cliente login backend
keycloak.login.client-id=${KEYCLOAK_LOGIN_CLIENT_ID:playland-login-backend}
keycloak.login.client-secret=${KEYCLOAK_LOGIN_CLIENT_SECRET:BdRE2FZ8d2QMB8u5Rpc5McxXEPz7ghGc}

# Resource server
spring.security.oauth2.resourceserver.jwt.issuer-uri=${JWT_ISSUER_URI:http://keycloak:8080/realms/playland-realm}
spring.security.oauth2.resourceserver.jwt.jwk-set-uri=${JWT_JWK_SET_URI:http://keycloak:8080/realms/playland-realm/protocol/openid-connect/certs}

management.endpoints.web.exposure.include=health,info

logging.level.org.springframework.security=TRACE
logging.level.org.springframework.security.oauth2=TRACE
logging.level.org.springframework.security.oauth2.server.resource=TRACE
logging.level.org.springframework.security.web=TRACE
logging.level.org.springframework.web=DEBUG
logging.level.org.springframework.web.cors=TRACE