spring.application.name=auth-service
server.port=8081
core-service.url=http://localhost:8083

# Base de datos
spring.datasource.url=jdbc:mysql://localhost:3306/playland_auth?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=123456
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# JWT CONFIGURATION
# ===============================
jwt.secret=playland-secret-key-super-long-123456789
jwt.expiration=600000
jwt.issuer=playlandmanager

# Actuator opcional
management.endpoints.web.exposure.include=health,info