version: "3.9"

services:
  mysql-auth:
    image: mysql:8.4
    container_name: mysql-auth
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: playland_auth
    ports:
      - "3307:3306"
    volumes:
      - mysql_auth_data:/var/lib/mysql
    networks:
      - playland-net
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-p123456"]
      interval: 10s
      timeout: 5s
      retries: 10

  mysql-catalogo:
    image: mysql:8.4
    container_name: mysql-catalogo
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: playland_catalogo
    ports:
      - "3308:3306"
    volumes:
      - mysql_catalogo_data:/var/lib/mysql
    networks:
      - playland-net
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-p123456"]
      interval: 10s
      timeout: 5s
      retries: 10

  mysql-core:
    image: mysql:8.4
    container_name: mysql-core
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: playland_core
    ports:
      - "3309:3306"
    volumes:
      - mysql_core_data:/var/lib/mysql
    networks:
      - playland-net
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-p123456"]
      interval: 10s
      timeout: 5s
      retries: 10

  postgres-keycloak:
    image: postgres:16
    container_name: postgres-keycloak
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: 123456
    ports:
      - "5433:5432"
    volumes:
      - postgres_keycloak_data:/var/lib/postgresql/data
    networks:
      - playland-net
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U keycloak -d keycloak"]
      interval: 10s
      timeout: 5s
      retries: 10

  keycloak:
    image: quay.io/keycloak/keycloak:26.1
    container_name: keycloak
    command: start-dev
    depends_on:
      postgres-keycloak:
        condition: service_healthy
    environment:
      KC_DB: postgres
      KC_DB_URL_HOST: postgres-keycloak
      KC_DB_URL_PORT: 5432
      KC_DB_URL_DATABASE: keycloak
      KC_DB_USERNAME: keycloak
      KC_DB_PASSWORD: 123456
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin123
    ports:
      - "9090:8080"
    networks:
      - playland-net

  auth-service:
    build:
      context: ./auth-service
    container_name: auth-service
    depends_on:
      mysql-auth:
        condition: service_healthy
    environment:
      SERVER_PORT: 8081
      CORE_SERVICE_URL: http://core-service:8083
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql-auth:3306/playland_auth?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: 123456
      SPRING_JPA_HIBERNATE_DDL_AUTO: update

      KEYCLOAK_SERVER_URL: http://keycloak:8080
      KEYCLOAK_REALM: playland-realm
      KEYCLOAK_LOGIN_CLIENT_ID: playland-login-backend
      KEYCLOAK_LOGIN_CLIENT_SECRET: BdRE2FZ8d2QMB8u5Rpc5McxXEPz7ghGc

      JWT_ISSUER_URI: http://keycloak:8080/realms/playland-realm
      JWT_JWK_SET_URI: http://keycloak:8080/realms/playland-realm/protocol/openid-connect/certs
    ports:
      - "8081:8081"
    networks:
      - playland-net

  catalogo-service:
    build:
      context: ./catalogo-service
    container_name: catalogo-service
    depends_on:
      mysql-catalogo:
        condition: service_healthy
    environment:
      SERVER_PORT: 8082
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql-catalogo:3306/playland_catalogo?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: 123456
      SPRING_JPA_HIBERNATE_DDL_AUTO: update

      JWT_ISSUER_URI: http://keycloak:8080/realms/playland-realm
      JWT_JWK_SET_URI: http://keycloak:8080/realms/playland-realm/protocol/openid-connect/certs
    ports:
      - "8082:8082"
    networks:
      - playland-net

  core-service:
    build:
      context: ./core-service
    container_name: core-service
    depends_on:
      mysql-core:
        condition: service_healthy
      auth-service:
        condition: service_started
      catalogo-service:
        condition: service_started
    environment:
      SERVER_PORT: 8083
      CATALOGO_SERVICE_URL: http://catalogo-service:8082
      AUTH_SERVICE_URL: http://auth-service:8081
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql-core:3306/playland_core?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: 123456
      SPRING_JPA_HIBERNATE_DDL_AUTO: update

      JWT_ISSUER_URI: http://keycloak:8080/realms/playland-realm
      JWT_JWK_SET_URI: http://keycloak:8080/realms/playland-realm/protocol/openid-connect/certs
    ports:
      - "8083:8083"
    networks:
      - playland-net

  api-gateway:
    build:
      context: ./api-gateway
    container_name: api-gateway
    depends_on:
      auth-service:
        condition: service_started
      catalogo-service:
        condition: service_started
      core-service:
        condition: service_started
      keycloak:
        condition: service_started
    environment:
      SERVER_PORT: 8080
      AUTH_SERVICE_URI: http://auth-service:8081
      CATALOGO_SERVICE_URI: http://catalogo-service:8082
      CORE_SERVICE_URI: http://core-service:8083

      JWT_ISSUER_URI: http://keycloak:8080/realms/playland-realm
      JWT_JWK_SET_URI: http://keycloak:8080/realms/playland-realm/protocol/openid-connect/certs
    ports:
      - "8080:8080"
    networks:
      - playland-net

volumes:
  mysql_auth_data:
  mysql_catalogo_data:
  mysql_core_data:
  postgres_keycloak_data:

networks:
  playland-net:
    driver: bridge