spring.application.name=api-gateway
server.port=${SERVER_PORT:8080}

spring.cloud.gateway.server.webflux.routes[0].id=auth-service
spring.cloud.gateway.server.webflux.routes[0].uri=${AUTH_SERVICE_URI:http://localhost:8081}
spring.cloud.gateway.server.webflux.routes[0].predicates[0]=Path=/api/auth/**

spring.cloud.gateway.server.webflux.routes[1].id=catalogo-service
spring.cloud.gateway.server.webflux.routes[1].uri=${CATALOGO_SERVICE_URI:http://localhost:8082}
spring.cloud.gateway.server.webflux.routes[1].predicates[0]=Path=/api/catalogo/**

spring.cloud.gateway.server.webflux.routes[2].id=core-service
spring.cloud.gateway.server.webflux.routes[2].uri=${CORE_SERVICE_URI:http://localhost:8083}
spring.cloud.gateway.server.webflux.routes[2].predicates[0]=Path=/api/core/**

spring.security.oauth2.resourceserver.jwt.issuer-uri=${JWT_ISSUER_URI:http://keycloak:8080/realms/playland-realm}
spring.security.oauth2.resourceserver.jwt.jwk-set-uri=${JWT_JWK_SET_URI:http://keycloak:8080/realms/playland-realm/protocol/openid-connect/certs}

management.endpoints.web.exposure.include=health,info