spring.application.name=core-service
server.port=${SERVER_PORT:8083}

catalogo-service.url=${CATALOGO_SERVICE_URL:http://localhost:8082}
auth-service.url=${AUTH_SERVICE_URL:http://localhost:8081}

# Base de datos
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3309/playland_core?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:root}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:123456}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

#JPA
spring.jpa.hibernate.ddl-auto=${SPRING_JPA_HIBERNATE_DDL_AUTO:update}
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.security.oauth2.resourceserver.jwt.issuer-uri=${JWT_ISSUER_URI:http://keycloak:8080/realms/playland-realm}
spring.security.oauth2.resourceserver.jwt.jwk-set-uri=${JWT_JWK_SET_URI:http://keycloak:8080/realms/playland-realm/protocol/openid-connect/certs}

management.endpoints.web.exposure.include=health,info

logging.level.org.springframework.security=TRACE
logging.level.org.springframework.security.oauth2=TRACE
logging.level.org.springframework.security.oauth2.server.resource=TRACE
logging.level.org.springframework.security.web.server=TRACE
logging.level.org.springframework.web.cors=TRACE
logging.level.org.springframework.web=DEBUG
logging.level.org.springframework.cloud.gateway=DEBUG
logging.level.org.springframework.web.reactive=DEBUG